services:
  backend:
    image: postgres:15-alpine
    container_name: iffa-hub-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: iffa_hub
    ports:
      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data

#volumes:
#  db_data: